const
    SET_LOADING = 'SET_LOADING',
    FETCH_USERS = 'FETCH_USERS',
    OPEN_NOTIFICATION = 'OPEN_NOTIFICATION',
    CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION',
    SET_ALERT = 'SET_ALERT',
    SET_USERS_TO_STORE = 'SET_USERS_TO_STORE',
    SELECT_USER = 'SELECT_USER',
    TOGGLE_ERROR_WINDOW_IS_OPEN = 'TOGGLE_ERROR_WINDOW_IS_OPEN';

export default {
    SET_LOADING,
    CLOSE_NOTIFICATION,
    FETCH_USERS,
    OPEN_NOTIFICATION,
    SET_ALERT,
    TOGGLE_ERROR_WINDOW_IS_OPEN,
    SELECT_USER,
    SET_USERS_TO_STORE
};
